
#### Global Settings

models:
  - aggregate_demographics_processor
  - aggregate_zone_processor
  - aggregate_zone_benefits
  - aggregate_od_processor
  - link_daily_processor
  - write_data_dictionary
  - write_tables

output_tables:
  action: include
  prefix: final_
  tables:
    - zone_demographics
    - aggregate_od_zone_summary
    - aggregate_od_district_summary
    - aggregate_zone_summary
    - aggregate_results

# resume_after: aggregate_zone_processor

dump: True
trace_od: [291, 216]

# values available to all processors
globals:
  DISCOUNT_RATE: 1.0
  ANNUALIZATION_FACTOR: 326 #Orange Line NS assumption
