
#### Global Settings

provenance: example_4step.configs

dump: True
trace_od: [727, 967]

# values available to all processors
globals:
  DISCOUNT_RATE: 1.0
  ANNUALIZATION_FACTOR: 326 #Orange Line NS assumption
  
#### Demographics / COCs Processor

#specify cocs
#note everybody is hard wired as 1.0 (100%)
#note * in the expressions means the expression applies to all cocs
coc_silos:
  - coc_lowinc
  - coc_medinc
  - coc_highinc
  - coc_veryhighinc
  - coc_ext_minority
  - coc_ext_lowengpro
  - coc_ext_age18or65
  - coc_lowinc_ext
  - everybody

# orig or dest
trip_coc_end: orig

# file name for cvals table csv data input file (expect versions in build and base data subdirs)
cval_file_name: mf.cval.csv

# file name for external cocs table csv data input file (expect versions in build and base data subdirs)
ext_cocs_file_name: cocs.csv

# values available to expressions in aggregate_demographics_processor
locals_aggregate_demographics:
  SAMPLE_CONSTANT: 42

#### Zones Processor

# file name for zones table csv data input files (expect versions in build and base data subdirs)
# data will be combined into a single table with columns names prefixed with 'base_' or 'build_'
# (e.g.) if ma.hbcdcls.csv has a column 'hbcdcls' you will have 'base_hbcdcls' and 'build_hbcdcls'
aggregate_zone_file_names:
  - ma.hbchdcls.csv
  - ma.hbcldcls.csv
  - ma.hbcmdcls.csv
  - ma.hbohdcls.csv
  - ma.hbomdcls.csv
  - ma.hboldcls.csv
  - ma.hbrhdcls.csv
  - ma.hbrldcls.csv
  - ma.hbrmdcls.csv
  - ma.hbsldcls.csv
  - ma.hbsmdcls.csv
  - ma.hbshdcls.csv
  - ma.hbwhdcls.csv
  - ma.hbwldcls.csv
  - ma.hbwmdcls.csv
  - ma.nhnwls.csv
  - ma.nhbwdcls.csv
  - ma.schdcls.csv
  - mf.cval.csv
  - ma.collprh.csv
  - ma.collprl.csv
  - ma.collprm.csv
  - ma.hboprh.csv
  - ma.hboprl.csv
  - ma.hboprm.csv
  - ma.hbrprh.csv
  - ma.hbrprl.csv
  - ma.hbrprm.csv
  - ma.hbsprh.csv
  - ma.hbsprl.csv
  - ma.hbsprm.csv
  - ma.hbwprh.csv
  - ma.hbwprl.csv
  - ma.hbwprm.csv
  - ma.nhnwpr.csv
  - ma.nhwpr.csv
  - ma.schpr.csv

# values available to expressions in aggregate_zone_processor
locals_aggregate_zone:
  #auto ownership variables
  ANNUAL_COST_PER_VEHICLE: 6611
  #utilities per minute (Kate IVT coefficients, use work for sch as well)
  UPM_HBC: 0.0346
  UPM_HBO: 0.0315
  UPM_HBR: 0.0315
  UPM_HBS: 0.0315
  UPM_HBW: 0.0414
  UPM_NHBNW: 0.0278
  UPM_NHBW: 0.0452
  UPM_SCH: 0.0414
  #value-of-time ($/hour; currently all equal, USDOT)
  VOT_HBC: 14.66
  VOT_HBO: 14.66
  VOT_HBR: 14.66
  VOT_HBS: 14.66
  VOT_HBW: 14.66
  VOT_NHBNW: 14.66
  VOT_NHBW: 14.66
  VOT_SCH: 14.66

#### OD Processor

aggregate_od_matrices:
  assign_mfs: assign_mfs.omx
  skims_mfs: skims_mfs.omx
  skims_mfs_rel: skims_mfs_rel.omx
  mode_choice_pa_hbo: mode_choice_pa_hbo.omx
  mode_choice_pa_hbr: mode_choice_pa_hbr.omx
  mode_choice_pa_hbs: mode_choice_pa_hbs.omx
  mode_choice_pa_hbw: mode_choice_pa_hbw.omx
  mode_choice_pa_nhw: mode_choice_pa_nhw.omx
  mode_choice_pa_nhnw: mode_choice_pa_nhnw.omx
  mode_choice_pa_sc: mode_choice_pa_sc.omx
  park_cost: parking_cost.omx
  
locals_aggregate_od:
  #time-of-day factors
  HBW_PK: 0.50
  HBW_OP: 0.50
  NHBW_PK: 0.50
  NHBW_OP: 0.50
  NHBNW_PK: 0.50
  NHBNW_OP: 0.50
  HBO_PK: 0.50
  HBO_OP: 0.50
  HBR_PK: 0.50
  HBR_OP: 0.50
  HBS_PK: 0.50
  HBS_OP: 0.50
  HBC_PK: 0.50
  HBC_OP: 0.50
  SCH_PK: 0.50
  SCH_OP: 0.50
  #value-of-time ($/hour; currently all equal, USDOT)
  VOT_HBC: 14.66
  VOT_HBO: 14.66
  VOT_HBR: 14.66
  VOT_HBS: 14.66
  VOT_HBW: 14.66
  VOT_NHBNW: 14.66
  VOT_NHBW: 14.66
  VOT_SCH: 14.66
  VOT_MEDTRK: 25.00
  VOT_HVYTRK: 38.00
  VOT_DRIVE_TRANSIT: 14.66

#### Link Daily Processor

link_daily_file_names:
  "": linksMD1.csv
  PM2: linksPM2.csv

link_daily_index_fields:
  - i
  - j

link_daily_table_column_map:
  i: i
  j: j
  "@zone" : zone
  "@amrmp" : amrmp
  "@cap" : cap
  "@centerturn" : centerturn
  "@divhwy" : divhwy
  "@dwdist" : dwdist
  "@fwcap" : fwcap
  "@htkad" : htkad
  "@htvol" : htvol
  "@hvol" : hvol
  "@lanes2" : lanes2
  "@lanes3" : lanes3
  "@lanes4" : lanes4
  "@losc" : losc
  "@loscart" : loscart
  "@losd" : losd
  "@lose" : lose
  "@losfh" : losfh
  "@losfl" : losfl
  "@losflart" : losflart
  "@mb" : mb
  "@mdrmp" : mdrmp
  "@mpa" : mpa
  "@mtkad" : mtkad
  "@mtvol" : mtvol
  "@noisef" : noisef
  "@pmrmp" : pmrmp
  "@relvar" : relvar
  "@signal" : signal
  "@spd35" : spd35
  "@spd40" : spd40
  "@spd45" : spd45
  "@spd50" : spd50
  "@spd50p" : spd50p
  "@spd70" : spd70
  "@speed" : speed
  "@stop" : stop
  "@svol" : svol
  "@tknet" : tknet
  "@tkpth" : tkpth
  "@trkad" : trkad
  "@ul3" : total link capacity
  "@updist" : updist
  "@urbrur" : urbrur
  "@waterf" : waterf
  "@barrier" : barrier
  additional_volume : additional_volume
  auto_time : auto_time
  auto_volume : auto_volume
  aux_transit_volume : aux_transit_volume
  data1 : data1
  data2 : data2
  data3 : data3
  length : length
  num_lanes : num_lanes
  type : type
  vertices : vertices
  volume_delay_func : volume_delay_func

# specify column name to enable zone tracing for both the o and the d zone
link_daily_od_column: zone

locals_link_daily:
  LINK_PEAK_TOD_SHARE_AUTO: 3.0
  LINK_OFFPEAK_TOD_SHARE_AUTO: 8.7
  LINK_PEAK_TOD_SHARE_TRANSIT: 3.2
  LINK_OFFPEAK_TOD_SHARE_TRANSIT: 6.1
  #Average Lane width
  LW_FWY: 12
  LW_HWY: 11.5
  LW_ART: 11.5
  #Average Inside Shoulder Width
  ISW_FWY: 8
  ISW_HWY: 3
  ISW_ART: 0
  #Average Outside Shoulder Width
  OSW_FWY: 11
  OSW_HWY: 10
  OSW_ART: 10
  #Crash Type Calibration Constants
  #Freeways
  CfwyF: 1.0
  CfwyI: 1.0
  CfwyP: 1.0
  #Rural Multi Lane
  CrxlU: 0.37
  CrxlD: 0.77
  #Rural Multi Lane Intersections
  Crxl3ST_X: 0.15
  Crxl4ST_X: 0.39
  Crxl4SG_X: 0.15
  #Rural 2 Lane
  Cr2l: 0.74
  #Rural 2 Lane Intersections
  Cr2l3ST_X: 0.31
  Cr2l4ST_X: 0.31
  Cr2l4SG_X: 0.45
  #Urban Arterials
  CU2U: 0.62
  CU3T: 0.81
  CU4D: 1.411
  CU4U: 0.63
  CU5T: 0.64
  #Urban Arterials Intersections
  CU3ST_X: 0.35
  CU4ST_X: 0.45
  CU3SG_X: 0.73
  CU4SG_X: 1.05
  # Proportion of fatal in F/I crashes from ODOT 2004-06 (http://www.oregon.gov/ODOT/Data/Pages/Crash.aspx)
  PERCENT_FATAL: 0.0212
  #Distribution of crashes on rural 2 lane highways
  R2L_PDO: 0.46
  R2L_I: 0.509
  R2L_F: 0.031
  #Number of driveways within roadway segment of driveway type
  #Major Commercial
  DMJC: 0.01
  #Minor Commercial
  DMNC: 0.01
  #Major Industrial/Institutional
  DMJI: 0.01
  #Minor Industrial/Institutional
  DMNI: 0.01
  #Major Residential
  DMJR: 0.01
  #Minor Residential
  DMNR: 0.01
  # Crash costs in Dollars
  CRASH_COST_PDO: 1522
  CRASH_COST_INJURY: 441800
  CRASH_COST_FATAL: 9400000
  # Water pollution cost
  WATER_POLLUTION_COST: 0.01625
  # Noise pollution cost
  NOISE_COST_AUTO_FREEWAY: 6.37
  NOISE_COST_AUTO_ARTERIAL: 1.545
  NOISE_COST_AUTO_COLLECTOR: 0.12
  NOISE_COST_MEDTRUCKS_FREEWAY: 19.17
  NOISE_COST_MEDTRUCKS_ARTERIAL: 10.945
  NOISE_COST_MEDTRUCKS_COLLECTOR: 1.86
  NOISE_COST_HEVTRUCKS_FREEWAY: 41.955
  NOISE_COST_HEVTRUCKS_ARTERIAL: 44.17
  NOISE_COST_HEVTRUCKS_COLLECTOR: 8.71
  #Vehicle operating cost
  GAS_COST: 2.80
  TRUCK_GAS_COST: 3.08
  GALLON_TO_BTU: 120524
  CAR_COST_PER_MILE: 0.0628
  TRUCK_COST_PER_MILE: 0.5070
  #emissions
  GRAMS_TO_METRIC_TONS: 0.000001
  CO2_COST: 51.81
  PM25_COST: 459000
  PM10_COST: 139000
  NOX_COST: 7300
  VOCS_COST: 37900
  CO2_PTYPE: 98
  PM25_PTYPE: 110
  PM10_PTYPE: 100
  NOX_PTYPE: 3
  VOCS_PTYPE: 87
  FUEL_CONSUMPTION_PTYPE: 92

tables_link_daily:
  EMISSIONS: moves_2010_summer_running_rates.csv