#Convert Metro demand model matrices to OMX
#Ben Stabler, ben.stabler@rsginc.com, 12/12/16
#Requires R OMX code - https://github.com/osPlanning/omx/tree/dev/api/r
#Which requires rhdf5 package from bioconductor

#Settings
#folder = "M:\\plan\\trms\\projects\\LCP\\Phase1\\reliability\\2040_FGBRT_new\\iter18\\model\\"
folder = "V:\\tbm\\kate\\_LCPtests\\updated\\2040_I205\\iter3_markets\\model\\"
omxFileName = "Kate_build_mode_choice_pa_sc.omx"
matNames = c("mf.hcwalk.cv23.m.pk.dat",
             "mf.hcwalk.cv23.m.op.dat",
             "mf.hcwalk.cv23.l.pk.dat",
             "mf.hcwalk.cv23.l.op.dat",
             "mf.hcwalk.cv23.h.pk.dat",
             "mf.hcwalk.cv23.h.op.dat",
             "mf.hcwalk.cv1.m.pk.dat",
             "mf.hcwalk.cv1.m.op.dat",
             "mf.hcwalk.cv1.l.pk.dat",
             "mf.hcwalk.cv1.l.op.dat",
             "mf.hcwalk.cv1.h.pk.dat",
             "mf.hcwalk.cv1.h.op.dat",
             "mf.hcwalk.cv0.m.pk.dat",
             "mf.hcwalk.cv0.m.op.dat",
             "mf.hcwalk.cv0.l.pk.dat",
             "mf.hcwalk.cv0.l.op.dat",
             "mf.hcwalk.cv0.h.pk.dat",
             "mf.hcwalk.cv0.h.op.dat",
             "mf.hctr.cv23.m.pk.dat",
             "mf.hctr.cv23.m.op.dat",
             "mf.hctr.cv23.l.pk.dat",
             "mf.hctr.cv23.l.op.dat",
             "mf.hctr.cv23.h.pk.dat",
             "mf.hctr.cv23.h.op.dat",
             "mf.hctr.cv1.m.pk.dat",
             "mf.hctr.cv1.m.op.dat",
             "mf.hctr.cv1.l.pk.dat",
             "mf.hctr.cv1.l.op.dat",
             "mf.hctr.cv1.h.pk.dat",
             "mf.hctr.cv1.h.op.dat",
             "mf.hctr.cv0.m.pk.dat",
             "mf.hctr.cv0.m.op.dat",
             "mf.hctr.cv0.l.pk.dat",
             "mf.hctr.cv0.l.op.dat",
             "mf.hctr.cv0.h.pk.dat",
             "mf.hctr.cv0.h.op.dat",
             "mf.hcprtrtl.cv23.m.pk.dat",
             "mf.hcprtrtl.cv23.m.op.dat",
             "mf.hcprtrtl.cv23.l.pk.dat",
             "mf.hcprtrtl.cv23.l.op.dat",
             "mf.hcprtrtl.cv23.h.pk.dat",
             "mf.hcprtrtl.cv23.h.op.dat",
             "mf.hcprtrtl.cv1.m.pk.dat",
             "mf.hcprtrtl.cv1.m.op.dat",
             "mf.hcprtrtl.cv1.l.pk.dat",
             "mf.hcprtrtl.cv1.l.op.dat",
             "mf.hcprtrtl.cv1.h.pk.dat",
             "mf.hcprtrtl.cv1.h.op.dat",
             "mf.hcprtrtd.cv23.m.pk.dat",
             "mf.hcprtrtd.cv23.m.op.dat",
             "mf.hcprtrtd.cv23.l.pk.dat",
             "mf.hcprtrtd.cv23.l.op.dat",
             "mf.hcprtrtd.cv23.h.pk.dat",
             "mf.hcprtrtd.cv23.h.op.dat",
             "mf.hcprtrtd.cv1.m.pk.dat",
             "mf.hcprtrtd.cv1.m.op.dat",
             "mf.hcprtrtd.cv1.l.pk.dat",
             "mf.hcprtrtd.cv1.l.op.dat",
             "mf.hcprtrtd.cv1.h.pk.dat",
             "mf.hcprtrtd.cv1.h.op.dat",
             "mf.hcprtr.cv23.m.pk.dat",
             "mf.hcprtr.cv23.m.op.dat",
             "mf.hcprtr.cv23.l.pk.dat",
             "mf.hcprtr.cv23.l.op.dat",
             "mf.hcprtr.cv23.h.pk.dat",
             "mf.hcprtr.cv23.h.op.dat",
             "mf.hcprtr.cv1.m.pk.dat",
             "mf.hcprtr.cv1.m.op.dat",
             "mf.hcprtr.cv1.l.pk.dat",
             "mf.hcprtr.cv1.l.op.dat",
             "mf.hcprtr.cv1.h.pk.dat",
             "mf.hcprtr.cv1.h.op.dat",
             "mf.hcpa.cv23.m.pk.dat",
             "mf.hcpa.cv23.m.op.dat",
             "mf.hcpa.cv23.l.pk.dat",
             "mf.hcpa.cv23.l.op.dat",
             "mf.hcpa.cv23.h.pk.dat",
             "mf.hcpa.cv23.h.op.dat",
             "mf.hcpa.cv1.m.pk.dat",
             "mf.hcpa.cv1.m.op.dat",
             "mf.hcpa.cv1.l.pk.dat",
             "mf.hcpa.cv1.l.op.dat",
             "mf.hcpa.cv1.h.pk.dat",
             "mf.hcpa.cv1.h.op.dat",
             "mf.hcpa.cv0.m.pk.dat",
             "mf.hcpa.cv0.m.op.dat",
             "mf.hcpa.cv0.l.pk.dat",
             "mf.hcpa.cv0.l.op.dat",
             "mf.hcpa.cv0.h.pk.dat",
             "mf.hcpa.cv0.h.op.dat",
             "mf.hcdp.cv23.m.pk.dat",
             "mf.hcdp.cv23.m.op.dat",
             "mf.hcdp.cv23.l.pk.dat",
             "mf.hcdp.cv23.l.op.dat",
             "mf.hcdp.cv23.h.pk.dat",
             "mf.hcdp.cv23.h.op.dat",
             "mf.hcdp.cv1.m.pk.dat",
             "mf.hcdp.cv1.m.op.dat",
             "mf.hcdp.cv1.l.pk.dat",
             "mf.hcdp.cv1.l.op.dat",
             "mf.hcdp.cv1.h.pk.dat",
             "mf.hcdp.cv1.h.op.dat",
             "mf.hcdp.cv0.m.pk.dat",
             "mf.hcdp.cv0.m.op.dat",
             "mf.hcdp.cv0.l.pk.dat",
             "mf.hcdp.cv0.l.op.dat",
             "mf.hcdp.cv0.h.pk.dat",
             "mf.hcdp.cv0.h.op.dat",
             "mf.hcda.cv23.m.pk.dat",
             "mf.hcda.cv23.m.op.dat",
             "mf.hcda.cv23.l.pk.dat",
             "mf.hcda.cv23.l.op.dat",
             "mf.hcda.cv23.h.pk.dat",
             "mf.hcda.cv23.h.op.dat",
             "mf.hcda.cv1.m.pk.dat",
             "mf.hcda.cv1.m.op.dat",
             "mf.hcda.cv1.l.pk.dat",
             "mf.hcda.cv1.l.op.dat",
             "mf.hcda.cv1.h.pk.dat",
             "mf.hcda.cv1.h.op.dat",
             "mf.hcda.cv0.m.pk.dat",
             "mf.hcda.cv0.m.op.dat",
             "mf.hcda.cv0.l.pk.dat",
             "mf.hcda.cv0.l.op.dat",
             "mf.hcda.cv0.h.pk.dat",
             "mf.hcda.cv0.h.op.dat",
             "mf.hcbike.cv23.m.pk.dat",
             "mf.hcbike.cv23.m.op.dat",
             "mf.hcbike.cv23.l.pk.dat",
             "mf.hcbike.cv23.l.op.dat",
             "mf.hcbike.cv23.h.pk.dat",
             "mf.hcbike.cv23.h.op.dat",
             "mf.hcbike.cv1.m.pk.dat",
             "mf.hcbike.cv1.m.op.dat",
             "mf.hcbike.cv1.l.pk.dat",
             "mf.hcbike.cv1.l.op.dat",
             "mf.hcbike.cv1.h.pk.dat",
             "mf.hcbike.cv1.h.op.dat",
             "mf.hcbike.cv0.m.pk.dat",
             "mf.hcbike.cv0.m.op.dat",
             "mf.hcbike.cv0.l.pk.dat",
             "mf.hcbike.cv0.l.op.dat",
             "mf.hcbike.cv0.h.pk.dat",
             "mf.hcbike.cv0.h.op.dat",
             "mf.schwalk.dat",
             "mf.schveh.dat",
             "mf.schtr.dat",
             "mf.schpas.dat",
             "mf.schbus.dat",
             "mf.schbike.dat"        
             )
             
numZones = 2162

#Create OMX matrix
setwd(folder)
source("omx.r") #Requires rhdf5 package from bioconductor
createFileOMX(omxFileName, numZones, numZones, 7)

for(m in matNames) {
  load(m)
  outName = gsub(".dat","",m)
  writeMatrixOMX(omxFileName, get(outName), outName)
}
