#Convert Metro demand model matrices to OMX
#Ben Stabler, ben.stabler@rsginc.com, 12/12/16
#Requires R OMX code - https://github.com/osPlanning/omx/tree/dev/api/r
#Which requires rhdf5 package from bioconductor

#Settings
#folder = "M:\\plan\\trms\\projects\\LCP\\Phase1\\reliability\\2040_FGBRT_new\\iter18\\model\\"
folder = "V:\\tbm\\kate\\_LCPtests\\updated\\2040_I205\\iter3_markets\\model\\"
omxFileName = "Kate_build_mode_choice_pa_hbo.omx"
matNames = c("mf.howalk.cv23.m.pk.dat",
             "mf.howalk.cv23.m.op.dat",
             "mf.howalk.cv23.l.pk.dat",
             "mf.howalk.cv23.l.op.dat",
             "mf.howalk.cv23.h.pk.dat",
             "mf.howalk.cv23.h.op.dat",
             "mf.howalk.cv1.m.pk.dat",
             "mf.howalk.cv1.m.op.dat",
             "mf.howalk.cv1.l.pk.dat",
             "mf.howalk.cv1.l.op.dat",
             "mf.howalk.cv1.h.pk.dat",
             "mf.howalk.cv1.h.op.dat",
             "mf.howalk.cv0.m.pk.dat",
             "mf.howalk.cv0.m.op.dat",
             "mf.howalk.cv0.l.pk.dat",
             "mf.howalk.cv0.l.op.dat",
             "mf.howalk.cv0.h.pk.dat",
             "mf.howalk.cv0.h.op.dat",
             "mf.hotr.cv23.m.pk.dat",
             "mf.hotr.cv23.m.op.dat",
             "mf.hotr.cv23.l.pk.dat",
             "mf.hotr.cv23.l.op.dat",
             "mf.hotr.cv23.h.pk.dat",
             "mf.hotr.cv23.h.op.dat",
             "mf.hotr.cv1.m.pk.dat",
             "mf.hotr.cv1.m.op.dat",
             "mf.hotr.cv1.l.pk.dat",
             "mf.hotr.cv1.l.op.dat",
             "mf.hotr.cv1.h.pk.dat",
             "mf.hotr.cv1.h.op.dat",
             "mf.hotr.cv0.m.pk.dat",
             "mf.hotr.cv0.m.op.dat",
             "mf.hotr.cv0.l.pk.dat",
             "mf.hotr.cv0.l.op.dat",
             "mf.hotr.cv0.h.pk.dat",
             "mf.hotr.cv0.h.op.dat",
             "mf.hoprtrtl.cv23.m.pk.dat",
             "mf.hoprtrtl.cv23.m.op.dat",
             "mf.hoprtrtl.cv23.l.pk.dat",
             "mf.hoprtrtl.cv23.l.op.dat",
             "mf.hoprtrtl.cv23.h.pk.dat",
             "mf.hoprtrtl.cv23.h.op.dat",
             "mf.hoprtrtl.cv1.m.pk.dat",
             "mf.hoprtrtl.cv1.m.op.dat",
             "mf.hoprtrtl.cv1.l.pk.dat",
             "mf.hoprtrtl.cv1.l.op.dat",
             "mf.hoprtrtl.cv1.h.pk.dat",
             "mf.hoprtrtl.cv1.h.op.dat",
             "mf.hoprtrtd.cv23.m.pk.dat",
             "mf.hoprtrtd.cv23.m.op.dat",
             "mf.hoprtrtd.cv23.l.pk.dat",
             "mf.hoprtrtd.cv23.l.op.dat",
             "mf.hoprtrtd.cv23.h.pk.dat",
             "mf.hoprtrtd.cv23.h.op.dat",
             "mf.hoprtrtd.cv1.m.pk.dat",
             "mf.hoprtrtd.cv1.m.op.dat",
             "mf.hoprtrtd.cv1.l.pk.dat",
             "mf.hoprtrtd.cv1.l.op.dat",
             "mf.hoprtrtd.cv1.h.pk.dat",
             "mf.hoprtrtd.cv1.h.op.dat",
             "mf.hoprtr.cv23.m.pk.dat",
             "mf.hoprtr.cv23.m.op.dat",
             "mf.hoprtr.cv23.l.pk.dat",
             "mf.hoprtr.cv23.l.op.dat",
             "mf.hoprtr.cv23.h.pk.dat",
             "mf.hoprtr.cv23.h.op.dat",
             "mf.hoprtr.cv1.m.pk.dat",
             "mf.hoprtr.cv1.m.op.dat",
             "mf.hoprtr.cv1.l.pk.dat",
             "mf.hoprtr.cv1.l.op.dat",
             "mf.hoprtr.cv1.h.pk.dat",
             "mf.hoprtr.cv1.h.op.dat",
             "mf.hopa.cv23.m.pk.dat",
             "mf.hopa.cv23.m.op.dat",
             "mf.hopa.cv23.l.pk.dat",
             "mf.hopa.cv23.l.op.dat",
             "mf.hopa.cv23.h.pk.dat",
             "mf.hopa.cv23.h.op.dat",
             "mf.hopa.cv1.m.pk.dat",
             "mf.hopa.cv1.m.op.dat",
             "mf.hopa.cv1.l.pk.dat",
             "mf.hopa.cv1.l.op.dat",
             "mf.hopa.cv1.h.pk.dat",
             "mf.hopa.cv1.h.op.dat",
             "mf.hopa.cv0.m.pk.dat",
             "mf.hopa.cv0.m.op.dat",
             "mf.hopa.cv0.l.pk.dat",
             "mf.hopa.cv0.l.op.dat",
             "mf.hopa.cv0.h.pk.dat",
             "mf.hopa.cv0.h.op.dat",
             "mf.hodp.cv23.m.pk.dat",
             "mf.hodp.cv23.m.op.dat",
             "mf.hodp.cv23.l.pk.dat",
             "mf.hodp.cv23.l.op.dat",
             "mf.hodp.cv23.h.pk.dat",
             "mf.hodp.cv23.h.op.dat",
             "mf.hodp.cv1.m.pk.dat",
             "mf.hodp.cv1.m.op.dat",
             "mf.hodp.cv1.l.pk.dat",
             "mf.hodp.cv1.l.op.dat",
             "mf.hodp.cv1.h.pk.dat",
             "mf.hodp.cv1.h.op.dat",
             "mf.hodp.cv0.m.pk.dat",
             "mf.hodp.cv0.m.op.dat",
             "mf.hodp.cv0.l.pk.dat",
             "mf.hodp.cv0.l.op.dat",
             "mf.hodp.cv0.h.pk.dat",
             "mf.hodp.cv0.h.op.dat",
             "mf.hoda.cv23.m.pk.dat",
             "mf.hoda.cv23.m.op.dat",
             "mf.hoda.cv23.l.pk.dat",
             "mf.hoda.cv23.l.op.dat",
             "mf.hoda.cv23.h.pk.dat",
             "mf.hoda.cv23.h.op.dat",
             "mf.hoda.cv1.m.pk.dat",
             "mf.hoda.cv1.m.op.dat",
             "mf.hoda.cv1.l.pk.dat",
             "mf.hoda.cv1.l.op.dat",
             "mf.hoda.cv1.h.pk.dat",
             "mf.hoda.cv1.h.op.dat",
             "mf.hoda.cv0.m.pk.dat",
             "mf.hoda.cv0.m.op.dat",
             "mf.hoda.cv0.l.pk.dat",
             "mf.hoda.cv0.l.op.dat",
             "mf.hoda.cv0.h.pk.dat",
             "mf.hoda.cv0.h.op.dat",
             "mf.hobike.cv23.m.pk.dat",
             "mf.hobike.cv23.m.op.dat",
             "mf.hobike.cv23.l.pk.dat",
             "mf.hobike.cv23.l.op.dat",
             "mf.hobike.cv23.h.pk.dat",
             "mf.hobike.cv23.h.op.dat",
             "mf.hobike.cv1.m.pk.dat",
             "mf.hobike.cv1.m.op.dat",
             "mf.hobike.cv1.l.pk.dat",
             "mf.hobike.cv1.l.op.dat",
             "mf.hobike.cv1.h.pk.dat",
             "mf.hobike.cv1.h.op.dat",
             "mf.hobike.cv0.m.pk.dat",
             "mf.hobike.cv0.m.op.dat",
             "mf.hobike.cv0.l.pk.dat",
             "mf.hobike.cv0.l.op.dat",
             "mf.hobike.cv0.h.pk.dat",
             "mf.hobike.cv0.h.op.dat"        
             )
             
numZones = 2162

#Create OMX matrix
setwd(folder)
source("V:/tbm/kate/_LCPtests/updated/2040_FC/iter0_markets/model/omx.r") #Requires rhdf5 package from bioconductor
createFileOMX(omxFileName, numZones, numZones, 7)

for(m in matNames) {
  load(m)
  outName = gsub(".dat","",m)
  writeMatrixOMX(omxFileName, get(outName), outName)
}
