#Convert Metro demand model matrices to OMX
#Ben Stabler, ben.stabler@rsginc.com, 12/12/16
#Requires R OMX code - https://github.com/osPlanning/omx/tree/dev/api/r
#Which requires rhdf5 package from bioconductor

#Settings
#folder = "M:\\plan\\trms\\projects\\LCP\\Phase1\\reliability\\2040_FGBRT_new\\iter18\\model\\"
folder = "V:\\tbm\\kate\\_LCPtests\\updated\\2040_I205\\iter3_markets\\model\\"
omxFileName = "Kate_build_mode_choice_pa_hbw.omx"
matNames = c("mf.hwwalk.cv23.m.pk.dat",
             "mf.hwwalk.cv23.m.op.dat",
             "mf.hwwalk.cv23.l.pk.dat",
             "mf.hwwalk.cv23.l.op.dat",
             "mf.hwwalk.cv23.h.pk.dat",
             "mf.hwwalk.cv23.h.op.dat",
             "mf.hwwalk.cv1.m.pk.dat",
             "mf.hwwalk.cv1.m.op.dat",
             "mf.hwwalk.cv1.l.pk.dat",
             "mf.hwwalk.cv1.l.op.dat",
             "mf.hwwalk.cv1.h.pk.dat",
             "mf.hwwalk.cv1.h.op.dat",
             "mf.hwwalk.cv0.m.pk.dat",
             "mf.hwwalk.cv0.m.op.dat",
             "mf.hwwalk.cv0.l.pk.dat",
             "mf.hwwalk.cv0.l.op.dat",
             "mf.hwwalk.cv0.h.pk.dat",
             "mf.hwwalk.cv0.h.op.dat",
             "mf.hwtr.cv23.m.pk.dat",
             "mf.hwtr.cv23.m.op.dat",
             "mf.hwtr.cv23.l.pk.dat",
             "mf.hwtr.cv23.l.op.dat",
             "mf.hwtr.cv23.h.pk.dat",
             "mf.hwtr.cv23.h.op.dat",
             "mf.hwtr.cv1.m.pk.dat",
             "mf.hwtr.cv1.m.op.dat",
             "mf.hwtr.cv1.l.pk.dat",
             "mf.hwtr.cv1.l.op.dat",
             "mf.hwtr.cv1.h.pk.dat",
             "mf.hwtr.cv1.h.op.dat",
             "mf.hwtr.cv0.m.pk.dat",
             "mf.hwtr.cv0.m.op.dat",
             "mf.hwtr.cv0.l.pk.dat",
             "mf.hwtr.cv0.l.op.dat",
             "mf.hwtr.cv0.h.pk.dat",
             "mf.hwtr.cv0.h.op.dat",
             "mf.hwprtrtl.cv23.m.pk.dat",
             "mf.hwprtrtl.cv23.m.op.dat",
             "mf.hwprtrtl.cv23.l.pk.dat",
             "mf.hwprtrtl.cv23.l.op.dat",
             "mf.hwprtrtl.cv23.h.pk.dat",
             "mf.hwprtrtl.cv23.h.op.dat",
             "mf.hwprtrtl.cv1.m.pk.dat",
             "mf.hwprtrtl.cv1.m.op.dat",
             "mf.hwprtrtl.cv1.l.pk.dat",
             "mf.hwprtrtl.cv1.l.op.dat",
             "mf.hwprtrtl.cv1.h.pk.dat",
             "mf.hwprtrtl.cv1.h.op.dat",
             "mf.hwprtrtd.cv23.m.pk.dat",
             "mf.hwprtrtd.cv23.m.op.dat",
             "mf.hwprtrtd.cv23.l.pk.dat",
             "mf.hwprtrtd.cv23.l.op.dat",
             "mf.hwprtrtd.cv23.h.pk.dat",
             "mf.hwprtrtd.cv23.h.op.dat",
             "mf.hwprtrtd.cv1.m.pk.dat",
             "mf.hwprtrtd.cv1.m.op.dat",
             "mf.hwprtrtd.cv1.l.pk.dat",
             "mf.hwprtrtd.cv1.l.op.dat",
             "mf.hwprtrtd.cv1.h.pk.dat",
             "mf.hwprtrtd.cv1.h.op.dat",
             "mf.hwprtr.cv23.m.pk.dat",
             "mf.hwprtr.cv23.m.op.dat",
             "mf.hwprtr.cv23.l.pk.dat",
             "mf.hwprtr.cv23.l.op.dat",
             "mf.hwprtr.cv23.h.pk.dat",
             "mf.hwprtr.cv23.h.op.dat",
             "mf.hwprtr.cv1.m.pk.dat",
             "mf.hwprtr.cv1.m.op.dat",
             "mf.hwprtr.cv1.l.pk.dat",
             "mf.hwprtr.cv1.l.op.dat",
             "mf.hwprtr.cv1.h.pk.dat",
             "mf.hwprtr.cv1.h.op.dat",
             "mf.hwpa.cv23.m.pk.dat",
             "mf.hwpa.cv23.m.op.dat",
             "mf.hwpa.cv23.l.pk.dat",
             "mf.hwpa.cv23.l.op.dat",
             "mf.hwpa.cv23.h.pk.dat",
             "mf.hwpa.cv23.h.op.dat",
             "mf.hwpa.cv1.m.pk.dat",
             "mf.hwpa.cv1.m.op.dat",
             "mf.hwpa.cv1.l.pk.dat",
             "mf.hwpa.cv1.l.op.dat",
             "mf.hwpa.cv1.h.pk.dat",
             "mf.hwpa.cv1.h.op.dat",
             "mf.hwpa.cv0.m.pk.dat",
             "mf.hwpa.cv0.m.op.dat",
             "mf.hwpa.cv0.l.pk.dat",
             "mf.hwpa.cv0.l.op.dat",
             "mf.hwpa.cv0.h.pk.dat",
             "mf.hwpa.cv0.h.op.dat",
             "mf.hwdp.cv23.m.pk.dat",
             "mf.hwdp.cv23.m.op.dat",
             "mf.hwdp.cv23.l.pk.dat",
             "mf.hwdp.cv23.l.op.dat",
             "mf.hwdp.cv23.h.pk.dat",
             "mf.hwdp.cv23.h.op.dat",
             "mf.hwdp.cv1.m.pk.dat",
             "mf.hwdp.cv1.m.op.dat",
             "mf.hwdp.cv1.l.pk.dat",
             "mf.hwdp.cv1.l.op.dat",
             "mf.hwdp.cv1.h.pk.dat",
             "mf.hwdp.cv1.h.op.dat",
             "mf.hwdp.cv0.m.pk.dat",
             "mf.hwdp.cv0.m.op.dat",
             "mf.hwdp.cv0.l.pk.dat",
             "mf.hwdp.cv0.l.op.dat",
             "mf.hwdp.cv0.h.pk.dat",
             "mf.hwdp.cv0.h.op.dat",
             "mf.hwda.cv23.m.pk.dat",
             "mf.hwda.cv23.m.op.dat",
             "mf.hwda.cv23.l.pk.dat",
             "mf.hwda.cv23.l.op.dat",
             "mf.hwda.cv23.h.pk.dat",
             "mf.hwda.cv23.h.op.dat",
             "mf.hwda.cv1.m.pk.dat",
             "mf.hwda.cv1.m.op.dat",
             "mf.hwda.cv1.l.pk.dat",
             "mf.hwda.cv1.l.op.dat",
             "mf.hwda.cv1.h.pk.dat",
             "mf.hwda.cv1.h.op.dat",
             "mf.hwda.cv0.m.pk.dat",
             "mf.hwda.cv0.m.op.dat",
             "mf.hwda.cv0.l.pk.dat",
             "mf.hwda.cv0.l.op.dat",
             "mf.hwda.cv0.h.pk.dat",
             "mf.hwda.cv0.h.op.dat",
             "mf.hwbike.cv23.m.pk.dat",
             "mf.hwbike.cv23.m.op.dat",
             "mf.hwbike.cv23.l.pk.dat",
             "mf.hwbike.cv23.l.op.dat",
             "mf.hwbike.cv23.h.pk.dat",
             "mf.hwbike.cv23.h.op.dat",
             "mf.hwbike.cv1.m.pk.dat",
             "mf.hwbike.cv1.m.op.dat",
             "mf.hwbike.cv1.l.pk.dat",
             "mf.hwbike.cv1.l.op.dat",
             "mf.hwbike.cv1.h.pk.dat",
             "mf.hwbike.cv1.h.op.dat",
             "mf.hwbike.cv0.m.pk.dat",
             "mf.hwbike.cv0.m.op.dat",
             "mf.hwbike.cv0.l.pk.dat",
             "mf.hwbike.cv0.l.op.dat",
             "mf.hwbike.cv0.h.pk.dat",
             "mf.hwbike.cv0.h.op.dat"        
             )
             
numZones = 2162

#Create OMX matrix
setwd(folder)
source("omx.r") #Requires rhdf5 package from bioconductor
createFileOMX(omxFileName, numZones, numZones, 7)

for(m in matNames) {
  load(m)
  outName = gsub(".dat","",m)
  writeMatrixOMX(omxFileName, get(outName), outName)
}
