#Convert Metro demand model matrices to OMX
#Ben Stabler, ben.stabler@rsginc.com, 12/12/16
#Requires R OMX code - https://github.com/osPlanning/omx/tree/dev/api/r
#Which requires rhdf5 package from bioconductor

#Settings
#folder = "M:\\plan\\trms\\projects\\LCP\\Phase1\\reliability\\2040_FGBRT_new\\iter18\\model\\"
folder = "V:\\tbm\\kate\\_LCPtests\\updated\\2040_I205\\iter3_markets\\model\\"
omxFileName = "Kate_build_mode_choice_pa_hbr.omx"
matNames = c("mf.hrwalk.cv23.m.pk.dat",
             "mf.hrwalk.cv23.m.op.dat",
             "mf.hrwalk.cv23.l.pk.dat",
             "mf.hrwalk.cv23.l.op.dat",
             "mf.hrwalk.cv23.h.pk.dat",
             "mf.hrwalk.cv23.h.op.dat",
             "mf.hrwalk.cv1.m.pk.dat",
             "mf.hrwalk.cv1.m.op.dat",
             "mf.hrwalk.cv1.l.pk.dat",
             "mf.hrwalk.cv1.l.op.dat",
             "mf.hrwalk.cv1.h.pk.dat",
             "mf.hrwalk.cv1.h.op.dat",
             "mf.hrwalk.cv0.m.pk.dat",
             "mf.hrwalk.cv0.m.op.dat",
             "mf.hrwalk.cv0.l.pk.dat",
             "mf.hrwalk.cv0.l.op.dat",
             "mf.hrwalk.cv0.h.pk.dat",
             "mf.hrwalk.cv0.h.op.dat",
             "mf.hrtr.cv23.m.pk.dat",
             "mf.hrtr.cv23.m.op.dat",
             "mf.hrtr.cv23.l.pk.dat",
             "mf.hrtr.cv23.l.op.dat",
             "mf.hrtr.cv23.h.pk.dat",
             "mf.hrtr.cv23.h.op.dat",
             "mf.hrtr.cv1.m.pk.dat",
             "mf.hrtr.cv1.m.op.dat",
             "mf.hrtr.cv1.l.pk.dat",
             "mf.hrtr.cv1.l.op.dat",
             "mf.hrtr.cv1.h.pk.dat",
             "mf.hrtr.cv1.h.op.dat",
             "mf.hrtr.cv0.m.pk.dat",
             "mf.hrtr.cv0.m.op.dat",
             "mf.hrtr.cv0.l.pk.dat",
             "mf.hrtr.cv0.l.op.dat",
             "mf.hrtr.cv0.h.pk.dat",
             "mf.hrtr.cv0.h.op.dat",
             "mf.hrprtrtl.cv23.m.pk.dat",
             "mf.hrprtrtl.cv23.m.op.dat",
             "mf.hrprtrtl.cv23.l.pk.dat",
             "mf.hrprtrtl.cv23.l.op.dat",
             "mf.hrprtrtl.cv23.h.pk.dat",
             "mf.hrprtrtl.cv23.h.op.dat",
             "mf.hrprtrtl.cv1.m.pk.dat",
             "mf.hrprtrtl.cv1.m.op.dat",
             "mf.hrprtrtl.cv1.l.pk.dat",
             "mf.hrprtrtl.cv1.l.op.dat",
             "mf.hrprtrtl.cv1.h.pk.dat",
             "mf.hrprtrtl.cv1.h.op.dat",
             "mf.hrprtrtd.cv23.m.pk.dat",
             "mf.hrprtrtd.cv23.m.op.dat",
             "mf.hrprtrtd.cv23.l.pk.dat",
             "mf.hrprtrtd.cv23.l.op.dat",
             "mf.hrprtrtd.cv23.h.pk.dat",
             "mf.hrprtrtd.cv23.h.op.dat",
             "mf.hrprtrtd.cv1.m.pk.dat",
             "mf.hrprtrtd.cv1.m.op.dat",
             "mf.hrprtrtd.cv1.l.pk.dat",
             "mf.hrprtrtd.cv1.l.op.dat",
             "mf.hrprtrtd.cv1.h.pk.dat",
             "mf.hrprtrtd.cv1.h.op.dat",
             "mf.hrprtr.cv23.m.pk.dat",
             "mf.hrprtr.cv23.m.op.dat",
             "mf.hrprtr.cv23.l.pk.dat",
             "mf.hrprtr.cv23.l.op.dat",
             "mf.hrprtr.cv23.h.pk.dat",
             "mf.hrprtr.cv23.h.op.dat",
             "mf.hrprtr.cv1.m.pk.dat",
             "mf.hrprtr.cv1.m.op.dat",
             "mf.hrprtr.cv1.l.pk.dat",
             "mf.hrprtr.cv1.l.op.dat",
             "mf.hrprtr.cv1.h.pk.dat",
             "mf.hrprtr.cv1.h.op.dat",
             "mf.hrpa.cv23.m.pk.dat",
             "mf.hrpa.cv23.m.op.dat",
             "mf.hrpa.cv23.l.pk.dat",
             "mf.hrpa.cv23.l.op.dat",
             "mf.hrpa.cv23.h.pk.dat",
             "mf.hrpa.cv23.h.op.dat",
             "mf.hrpa.cv1.m.pk.dat",
             "mf.hrpa.cv1.m.op.dat",
             "mf.hrpa.cv1.l.pk.dat",
             "mf.hrpa.cv1.l.op.dat",
             "mf.hrpa.cv1.h.pk.dat",
             "mf.hrpa.cv1.h.op.dat",
             "mf.hrpa.cv0.m.pk.dat",
             "mf.hrpa.cv0.m.op.dat",
             "mf.hrpa.cv0.l.pk.dat",
             "mf.hrpa.cv0.l.op.dat",
             "mf.hrpa.cv0.h.pk.dat",
             "mf.hrpa.cv0.h.op.dat",
             "mf.hrdp.cv23.m.pk.dat",
             "mf.hrdp.cv23.m.op.dat",
             "mf.hrdp.cv23.l.pk.dat",
             "mf.hrdp.cv23.l.op.dat",
             "mf.hrdp.cv23.h.pk.dat",
             "mf.hrdp.cv23.h.op.dat",
             "mf.hrdp.cv1.m.pk.dat",
             "mf.hrdp.cv1.m.op.dat",
             "mf.hrdp.cv1.l.pk.dat",
             "mf.hrdp.cv1.l.op.dat",
             "mf.hrdp.cv1.h.pk.dat",
             "mf.hrdp.cv1.h.op.dat",
             "mf.hrdp.cv0.m.pk.dat",
             "mf.hrdp.cv0.m.op.dat",
             "mf.hrdp.cv0.l.pk.dat",
             "mf.hrdp.cv0.l.op.dat",
             "mf.hrdp.cv0.h.pk.dat",
             "mf.hrdp.cv0.h.op.dat",
             "mf.hrda.cv23.m.pk.dat",
             "mf.hrda.cv23.m.op.dat",
             "mf.hrda.cv23.l.pk.dat",
             "mf.hrda.cv23.l.op.dat",
             "mf.hrda.cv23.h.pk.dat",
             "mf.hrda.cv23.h.op.dat",
             "mf.hrda.cv1.m.pk.dat",
             "mf.hrda.cv1.m.op.dat",
             "mf.hrda.cv1.l.pk.dat",
             "mf.hrda.cv1.l.op.dat",
             "mf.hrda.cv1.h.pk.dat",
             "mf.hrda.cv1.h.op.dat",
             "mf.hrda.cv0.m.pk.dat",
             "mf.hrda.cv0.m.op.dat",
             "mf.hrda.cv0.l.pk.dat",
             "mf.hrda.cv0.l.op.dat",
             "mf.hrda.cv0.h.pk.dat",
             "mf.hrda.cv0.h.op.dat",
             "mf.hrbike.cv23.m.pk.dat",
             "mf.hrbike.cv23.m.op.dat",
             "mf.hrbike.cv23.l.pk.dat",
             "mf.hrbike.cv23.l.op.dat",
             "mf.hrbike.cv23.h.pk.dat",
             "mf.hrbike.cv23.h.op.dat",
             "mf.hrbike.cv1.m.pk.dat",
             "mf.hrbike.cv1.m.op.dat",
             "mf.hrbike.cv1.l.pk.dat",
             "mf.hrbike.cv1.l.op.dat",
             "mf.hrbike.cv1.h.pk.dat",
             "mf.hrbike.cv1.h.op.dat",
             "mf.hrbike.cv0.m.pk.dat",
             "mf.hrbike.cv0.m.op.dat",
             "mf.hrbike.cv0.l.pk.dat",
             "mf.hrbike.cv0.l.op.dat",
             "mf.hrbike.cv0.h.pk.dat",
             "mf.hrbike.cv0.h.op.dat"        
             )
             
numZones = 2162

#Create OMX matrix
setwd(folder)
source("omx.r") #Requires rhdf5 package from bioconductor
createFileOMX(omxFileName, numZones, numZones, 7)

for(m in matNames) {
  load(m)
  outName = gsub(".dat","",m)
  writeMatrixOMX(omxFileName, get(outName), outName)
}
