#Convert Metro demand model matrices to OMX
#Ben Stabler, ben.stabler@rsginc.com, 12/12/16
#Requires R OMX code - https://github.com/osPlanning/omx/tree/dev/api/r
#Which requires rhdf5 package from bioconductor

#Settings
#folder = "M:\\plan\\trms\\projects\\LCP\\Phase1\\reliability\\2040_FGBRT_new\\iter18\\model\\"
folder = "V:\\tbm\\kate\\_LCPtests\\updated\\2040_I205\\iter3_markets\\model\\"
omxFileName = "Kate_build_mode_choice_pa_hbs.omx"
matNames = c("mf.hswalk.cv23.m.pk.dat",
             "mf.hswalk.cv23.m.op.dat",
             "mf.hswalk.cv23.l.pk.dat",
             "mf.hswalk.cv23.l.op.dat",
             "mf.hswalk.cv23.h.pk.dat",
             "mf.hswalk.cv23.h.op.dat",
             "mf.hswalk.cv1.m.pk.dat",
             "mf.hswalk.cv1.m.op.dat",
             "mf.hswalk.cv1.l.pk.dat",
             "mf.hswalk.cv1.l.op.dat",
             "mf.hswalk.cv1.h.pk.dat",
             "mf.hswalk.cv1.h.op.dat",
             "mf.hswalk.cv0.m.pk.dat",
             "mf.hswalk.cv0.m.op.dat",
             "mf.hswalk.cv0.l.pk.dat",
             "mf.hswalk.cv0.l.op.dat",
             "mf.hswalk.cv0.h.pk.dat",
             "mf.hswalk.cv0.h.op.dat",
             "mf.hstr.cv23.m.pk.dat",
             "mf.hstr.cv23.m.op.dat",
             "mf.hstr.cv23.l.pk.dat",
             "mf.hstr.cv23.l.op.dat",
             "mf.hstr.cv23.h.pk.dat",
             "mf.hstr.cv23.h.op.dat",
             "mf.hstr.cv1.m.pk.dat",
             "mf.hstr.cv1.m.op.dat",
             "mf.hstr.cv1.l.pk.dat",
             "mf.hstr.cv1.l.op.dat",
             "mf.hstr.cv1.h.pk.dat",
             "mf.hstr.cv1.h.op.dat",
             "mf.hstr.cv0.m.pk.dat",
             "mf.hstr.cv0.m.op.dat",
             "mf.hstr.cv0.l.pk.dat",
             "mf.hstr.cv0.l.op.dat",
             "mf.hstr.cv0.h.pk.dat",
             "mf.hstr.cv0.h.op.dat",
             "mf.hsprtrtl.cv23.m.pk.dat",
             "mf.hsprtrtl.cv23.m.op.dat",
             "mf.hsprtrtl.cv23.l.pk.dat",
             "mf.hsprtrtl.cv23.l.op.dat",
             "mf.hsprtrtl.cv23.h.pk.dat",
             "mf.hsprtrtl.cv23.h.op.dat",
             "mf.hsprtrtl.cv1.m.pk.dat",
             "mf.hsprtrtl.cv1.m.op.dat",
             "mf.hsprtrtl.cv1.l.pk.dat",
             "mf.hsprtrtl.cv1.l.op.dat",
             "mf.hsprtrtl.cv1.h.pk.dat",
             "mf.hsprtrtl.cv1.h.op.dat",
             "mf.hsprtrtd.cv23.m.pk.dat",
             "mf.hsprtrtd.cv23.m.op.dat",
             "mf.hsprtrtd.cv23.l.pk.dat",
             "mf.hsprtrtd.cv23.l.op.dat",
             "mf.hsprtrtd.cv23.h.pk.dat",
             "mf.hsprtrtd.cv23.h.op.dat",
             "mf.hsprtrtd.cv1.m.pk.dat",
             "mf.hsprtrtd.cv1.m.op.dat",
             "mf.hsprtrtd.cv1.l.pk.dat",
             "mf.hsprtrtd.cv1.l.op.dat",
             "mf.hsprtrtd.cv1.h.pk.dat",
             "mf.hsprtrtd.cv1.h.op.dat",
             "mf.hsprtr.cv23.m.pk.dat",
             "mf.hsprtr.cv23.m.op.dat",
             "mf.hsprtr.cv23.l.pk.dat",
             "mf.hsprtr.cv23.l.op.dat",
             "mf.hsprtr.cv23.h.pk.dat",
             "mf.hsprtr.cv23.h.op.dat",
             "mf.hsprtr.cv1.m.pk.dat",
             "mf.hsprtr.cv1.m.op.dat",
             "mf.hsprtr.cv1.l.pk.dat",
             "mf.hsprtr.cv1.l.op.dat",
             "mf.hsprtr.cv1.h.pk.dat",
             "mf.hsprtr.cv1.h.op.dat",
             "mf.hspa.cv23.m.pk.dat",
             "mf.hspa.cv23.m.op.dat",
             "mf.hspa.cv23.l.pk.dat",
             "mf.hspa.cv23.l.op.dat",
             "mf.hspa.cv23.h.pk.dat",
             "mf.hspa.cv23.h.op.dat",
             "mf.hspa.cv1.m.pk.dat",
             "mf.hspa.cv1.m.op.dat",
             "mf.hspa.cv1.l.pk.dat",
             "mf.hspa.cv1.l.op.dat",
             "mf.hspa.cv1.h.pk.dat",
             "mf.hspa.cv1.h.op.dat",
             "mf.hspa.cv0.m.pk.dat",
             "mf.hspa.cv0.m.op.dat",
             "mf.hspa.cv0.l.pk.dat",
             "mf.hspa.cv0.l.op.dat",
             "mf.hspa.cv0.h.pk.dat",
             "mf.hspa.cv0.h.op.dat",
             "mf.hsdp.cv23.m.pk.dat",
             "mf.hsdp.cv23.m.op.dat",
             "mf.hsdp.cv23.l.pk.dat",
             "mf.hsdp.cv23.l.op.dat",
             "mf.hsdp.cv23.h.pk.dat",
             "mf.hsdp.cv23.h.op.dat",
             "mf.hsdp.cv1.m.pk.dat",
             "mf.hsdp.cv1.m.op.dat",
             "mf.hsdp.cv1.l.pk.dat",
             "mf.hsdp.cv1.l.op.dat",
             "mf.hsdp.cv1.h.pk.dat",
             "mf.hsdp.cv1.h.op.dat",
             "mf.hsdp.cv0.m.pk.dat",
             "mf.hsdp.cv0.m.op.dat",
             "mf.hsdp.cv0.l.pk.dat",
             "mf.hsdp.cv0.l.op.dat",
             "mf.hsdp.cv0.h.pk.dat",
             "mf.hsdp.cv0.h.op.dat",
             "mf.hsda.cv23.m.pk.dat",
             "mf.hsda.cv23.m.op.dat",
             "mf.hsda.cv23.l.pk.dat",
             "mf.hsda.cv23.l.op.dat",
             "mf.hsda.cv23.h.pk.dat",
             "mf.hsda.cv23.h.op.dat",
             "mf.hsda.cv1.m.pk.dat",
             "mf.hsda.cv1.m.op.dat",
             "mf.hsda.cv1.l.pk.dat",
             "mf.hsda.cv1.l.op.dat",
             "mf.hsda.cv1.h.pk.dat",
             "mf.hsda.cv1.h.op.dat",
             "mf.hsda.cv0.m.pk.dat",
             "mf.hsda.cv0.m.op.dat",
             "mf.hsda.cv0.l.pk.dat",
             "mf.hsda.cv0.l.op.dat",
             "mf.hsda.cv0.h.pk.dat",
             "mf.hsda.cv0.h.op.dat",
             "mf.hsbike.cv23.m.pk.dat",
             "mf.hsbike.cv23.m.op.dat",
             "mf.hsbike.cv23.l.pk.dat",
             "mf.hsbike.cv23.l.op.dat",
             "mf.hsbike.cv23.h.pk.dat",
             "mf.hsbike.cv23.h.op.dat",
             "mf.hsbike.cv1.m.pk.dat",
             "mf.hsbike.cv1.m.op.dat",
             "mf.hsbike.cv1.l.pk.dat",
             "mf.hsbike.cv1.l.op.dat",
             "mf.hsbike.cv1.h.pk.dat",
             "mf.hsbike.cv1.h.op.dat",
             "mf.hsbike.cv0.m.pk.dat",
             "mf.hsbike.cv0.m.op.dat",
             "mf.hsbike.cv0.l.pk.dat",
             "mf.hsbike.cv0.l.op.dat",
             "mf.hsbike.cv0.h.pk.dat",
             "mf.hsbike.cv0.h.op.dat"        
             )
             
numZones = 2162

#Create OMX matrix
setwd(folder)
source("omx.r") #Requires rhdf5 package from bioconductor
createFileOMX(omxFileName, numZones, numZones, 7)

for(m in matNames) {
  load(m)
  outName = gsub(".dat","",m)
  writeMatrixOMX(omxFileName, get(outName), outName)
}
