#Convert Metro demand model matrices to OMX
#Ben Stabler, ben.stabler@rsginc.com, 12/12/16
#Requires R OMX code - https://github.com/osPlanning/omx/tree/dev/api/r
#Which requires rhdf5 package from bioconductor

#Settings
#folder = "M:\\plan\\trms\\projects\\LCP\\Phase1\\reliability\\2040_FGBRT_new\\iter18\\model\\"
folder = "V:\\tbm\\kate\\_LCPtests\\updated\\2040_I205\\iter3_markets\\model\\"
omxFileName = "Kate_build_mode_choice_pa_nhnw.omx"
matNames = c("mf.nhnwwalk.cv23.m.pk.dat",
             "mf.nhnwwalk.cv23.m.op.dat",
             "mf.nhnwwalk.cv23.l.pk.dat",
             "mf.nhnwwalk.cv23.l.op.dat",
             "mf.nhnwwalk.cv23.h.pk.dat",
             "mf.nhnwwalk.cv23.h.op.dat",
             "mf.nhnwwalk.cv1.m.pk.dat",
             "mf.nhnwwalk.cv1.m.op.dat",
             "mf.nhnwwalk.cv1.l.pk.dat",
             "mf.nhnwwalk.cv1.l.op.dat",
             "mf.nhnwwalk.cv1.h.pk.dat",
             "mf.nhnwwalk.cv1.h.op.dat",
             "mf.nhnwwalk.cv0.m.pk.dat",
             "mf.nhnwwalk.cv0.m.op.dat",
             "mf.nhnwwalk.cv0.l.pk.dat",
             "mf.nhnwwalk.cv0.l.op.dat",
             "mf.nhnwwalk.cv0.h.pk.dat",
             "mf.nhnwwalk.cv0.h.op.dat",
             "mf.nhnwtr.cv23.m.pk.dat",
             "mf.nhnwtr.cv23.m.op.dat",
             "mf.nhnwtr.cv23.l.pk.dat",
             "mf.nhnwtr.cv23.l.op.dat",
             "mf.nhnwtr.cv23.h.pk.dat",
             "mf.nhnwtr.cv23.h.op.dat",
             "mf.nhnwtr.cv1.m.pk.dat",
             "mf.nhnwtr.cv1.m.op.dat",
             "mf.nhnwtr.cv1.l.pk.dat",
             "mf.nhnwtr.cv1.l.op.dat",
             "mf.nhnwtr.cv1.h.pk.dat",
             "mf.nhnwtr.cv1.h.op.dat",
             "mf.nhnwtr.cv0.m.pk.dat",
             "mf.nhnwtr.cv0.m.op.dat",
             "mf.nhnwtr.cv0.l.pk.dat",
             "mf.nhnwtr.cv0.l.op.dat",
             "mf.nhnwtr.cv0.h.pk.dat",
             "mf.nhnwtr.cv0.h.op.dat",
             "mf.nhnwpa.cv23.m.pk.dat",
             "mf.nhnwpa.cv23.m.op.dat",
             "mf.nhnwpa.cv23.l.pk.dat",
             "mf.nhnwpa.cv23.l.op.dat",
             "mf.nhnwpa.cv23.h.pk.dat",
             "mf.nhnwpa.cv23.h.op.dat",
             "mf.nhnwpa.cv1.m.pk.dat",
             "mf.nhnwpa.cv1.m.op.dat",
             "mf.nhnwpa.cv1.l.pk.dat",
             "mf.nhnwpa.cv1.l.op.dat",
             "mf.nhnwpa.cv1.h.pk.dat",
             "mf.nhnwpa.cv1.h.op.dat",
             "mf.nhnwpa.cv0.m.pk.dat",
             "mf.nhnwpa.cv0.m.op.dat",
             "mf.nhnwpa.cv0.l.pk.dat",
             "mf.nhnwpa.cv0.l.op.dat",
             "mf.nhnwpa.cv0.h.pk.dat",
             "mf.nhnwpa.cv0.h.op.dat",
             "mf.nhnwdp.cv23.m.pk.dat",
             "mf.nhnwdp.cv23.m.op.dat",
             "mf.nhnwdp.cv23.l.pk.dat",
             "mf.nhnwdp.cv23.l.op.dat",
             "mf.nhnwdp.cv23.h.pk.dat",
             "mf.nhnwdp.cv23.h.op.dat",
             "mf.nhnwdp.cv1.m.pk.dat",
             "mf.nhnwdp.cv1.m.op.dat",
             "mf.nhnwdp.cv1.l.pk.dat",
             "mf.nhnwdp.cv1.l.op.dat",
             "mf.nhnwdp.cv1.h.pk.dat",
             "mf.nhnwdp.cv1.h.op.dat",
             "mf.nhnwdp.cv0.m.pk.dat",
             "mf.nhnwdp.cv0.m.op.dat",
             "mf.nhnwdp.cv0.l.pk.dat",
             "mf.nhnwdp.cv0.l.op.dat",
             "mf.nhnwdp.cv0.h.pk.dat",
             "mf.nhnwdp.cv0.h.op.dat",
             "mf.nhnwda.cv23.m.pk.dat",
             "mf.nhnwda.cv23.m.op.dat",
             "mf.nhnwda.cv23.l.pk.dat",
             "mf.nhnwda.cv23.l.op.dat",
             "mf.nhnwda.cv23.h.pk.dat",
             "mf.nhnwda.cv23.h.op.dat",
             "mf.nhnwda.cv1.m.pk.dat",
             "mf.nhnwda.cv1.m.op.dat",
             "mf.nhnwda.cv1.l.pk.dat",
             "mf.nhnwda.cv1.l.op.dat",
             "mf.nhnwda.cv1.h.pk.dat",
             "mf.nhnwda.cv1.h.op.dat",
             "mf.nhnwda.cv0.m.pk.dat",
             "mf.nhnwda.cv0.m.op.dat",
             "mf.nhnwda.cv0.l.pk.dat",
             "mf.nhnwda.cv0.l.op.dat",
             "mf.nhnwda.cv0.h.pk.dat",
             "mf.nhnwda.cv0.h.op.dat",
             "mf.nhnwbike.cv23.m.pk.dat",
             "mf.nhnwbike.cv23.m.op.dat",
             "mf.nhnwbike.cv23.l.pk.dat",
             "mf.nhnwbike.cv23.l.op.dat",
             "mf.nhnwbike.cv23.h.pk.dat",
             "mf.nhnwbike.cv23.h.op.dat",
             "mf.nhnwbike.cv1.m.pk.dat",
             "mf.nhnwbike.cv1.m.op.dat",
             "mf.nhnwbike.cv1.l.pk.dat",
             "mf.nhnwbike.cv1.l.op.dat",
             "mf.nhnwbike.cv1.h.pk.dat",
             "mf.nhnwbike.cv1.h.op.dat",
             "mf.nhnwbike.cv0.m.pk.dat",
             "mf.nhnwbike.cv0.m.op.dat",
             "mf.nhnwbike.cv0.l.pk.dat",
             "mf.nhnwbike.cv0.l.op.dat",
             "mf.nhnwbike.cv0.h.pk.dat",
             "mf.nhnwbike.cv0.h.op.dat"        
             )
             
numZones = 2162

#Create OMX matrix
setwd(folder)
source("omx.r") #Requires rhdf5 package from bioconductor
createFileOMX(omxFileName, numZones, numZones, 7)

for(m in matNames) {
  load(m)
  outName = gsub(".dat","",m)
  writeMatrixOMX(omxFileName, get(outName), outName)
}
