#Calculate ITHIM benefit dollars for MCE
#Ben Stabler, ben.stabler@rsginc.com, 07/25/17
#Updated 10/3/18 to work with MCE Kate integrated workflow

#settings
projectDirectory_base = "data/base-data"
projectDirectory_build = "data/build-data"
projectDirectory_run = "data/ithimR"

GBDFileForITHIM = "burden.portland.csv"
PopulationFileForITHIM = "F.portland.csv"

WALK_SPEED = 3
BIKE_SPEED = 10
AVG_HH_SIZE = 2.4
DOLLARS_PER_DALY = 80000

#load ITHIM (and download ITHIM package if needed)
if (!require(devtools)) {
  install.packages("devtools")
}
if (!require(ITHIM)) {
  library("devtools")
  devtools::install_github("ITHIM/ITHIM", ref="version2")
}
if (!require(omxr)) {
  devtools::install_github("gregmacfarlane/omxr")
}
if (!require(rhdf5)) {
  source("https://bioconductor.org/biocLite.R")
  biocLite(c("rhdf5","zlibbioc"), suppressUpdates=TRUE, quiet=TRUE)
}
library("ITHIM")
library(omxr)

#read skims and cocs
print("read skims and cocs")
init_dir = getwd()
setwd(projectDirectory_base)
base_tdist = read_omx("mce_input_skims.omx","mf.tdist")
base_wdist = read_omx("mce_input_skims.omx","mf.wdist")
cvals = read.csv("mce_input_cval.csv") #hhs by cval by zone
cocs = read.csv("cocs.csv") #minority, lowengpro, age18or65, lowinc

setwd(init_dir)
setwd(projectDirectory_build)
build_tdist = read_omx("mce_input_skims.omx","mf.tdist")
build_wdist = read_omx("mce_input_skims.omx","mf.wdist")

#read demand matrices base
print("read demand matrices base")
setwd(init_dir)
setwd(projectDirectory_base)
base_walk_trips = read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv0.l.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv0.l.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv0.m.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv0.m.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv0.h.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv0.h.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv1.l.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv1.l.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv1.m.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv1.m.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv1.h.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv1.h.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv23.l.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv23.l.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv23.m.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv23.m.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv23.h.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv23.h.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv0.l.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv0.l.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv0.m.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv0.m.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv0.h.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv0.h.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv1.l.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv1.l.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv1.m.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv1.m.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv1.h.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv1.h.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv23.l.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv23.l.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv23.m.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv23.m.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv23.h.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv23.h.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv0.l.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv0.l.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv0.m.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv0.m.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv0.h.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv0.h.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv1.l.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv1.l.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv1.m.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv1.m.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv1.h.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv1.h.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv23.l.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv23.l.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv23.m.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv23.m.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv23.h.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv23.h.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv0.l.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv0.l.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv0.m.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv0.m.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv0.h.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv0.h.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv1.l.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv1.l.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv1.m.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv1.m.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv1.h.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv1.h.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv23.l.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv23.l.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv23.m.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv23.m.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv23.h.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv23.h.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv0.l.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv0.l.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv0.m.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv0.m.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv0.h.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv0.h.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv1.l.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv1.l.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv1.m.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv1.m.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv1.h.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv1.h.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv23.l.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv23.l.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv23.m.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv23.m.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv23.h.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv23.h.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv0.l.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv0.l.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv0.m.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv0.m.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv0.h.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv0.h.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv1.l.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv1.l.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv1.m.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv1.m.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv1.h.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv1.h.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv23.l.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv23.l.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv23.m.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv23.m.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv23.h.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv23.h.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_sch.omx","mf.schwalk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv0.l.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv0.l.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv0.m.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv0.m.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv0.h.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv0.h.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv1.l.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv1.l.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv1.m.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv1.m.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv1.h.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv1.h.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv23.l.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv23.l.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv23.m.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv23.m.op")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv23.h.pk")
base_walk_trips = base_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv23.h.op")

base_bike_trips = read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv0.l.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv0.l.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv0.m.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv0.m.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv0.h.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv0.h.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv1.l.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv1.l.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv1.m.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv1.m.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv1.h.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv1.h.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv23.l.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv23.l.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv23.m.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv23.m.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv23.h.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv23.h.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv0.l.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv0.l.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv0.m.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv0.m.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv0.h.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv0.h.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv1.l.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv1.l.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv1.m.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv1.m.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv1.h.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv1.h.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv23.l.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv23.l.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv23.m.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv23.m.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv23.h.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv23.h.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv0.l.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv0.l.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv0.m.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv0.m.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv0.h.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv0.h.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv1.l.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv1.l.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv1.m.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv1.m.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv1.h.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv1.h.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv23.l.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv23.l.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv23.m.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv23.m.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv23.h.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv23.h.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv0.l.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv0.l.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv0.m.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv0.m.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv0.h.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv0.h.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv1.l.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv1.l.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv1.m.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv1.m.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv1.h.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv1.h.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv23.l.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv23.l.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv23.m.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv23.m.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv23.h.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv23.h.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv0.l.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv0.l.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv0.m.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv0.m.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv0.h.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv0.h.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv1.l.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv1.l.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv1.m.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv1.m.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv1.h.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv1.h.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv23.l.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv23.l.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv23.m.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv23.m.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv23.h.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv23.h.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv0.l.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv0.l.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv0.m.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv0.m.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv0.h.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv0.h.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv1.l.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv1.l.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv1.m.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv1.m.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv1.h.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv1.h.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv23.l.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv23.l.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv23.m.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv23.m.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv23.h.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv23.h.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_sch.omx","mf.schbike")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv0.l.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv0.l.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv0.m.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv0.m.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv0.h.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv0.h.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv1.l.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv1.l.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv1.m.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv1.m.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv1.h.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv1.h.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv23.l.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv23.l.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv23.m.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv23.m.op")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv23.h.pk")
base_bike_trips = base_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv23.h.op")

#read demand matrices build
print("read demand matrices build")
setwd(init_dir)
setwd(projectDirectory_build)
build_walk_trips = read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv0.l.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv0.l.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv0.m.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv0.m.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv0.h.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv0.h.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv1.l.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv1.l.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv1.m.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv1.m.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv1.h.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv1.h.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv23.l.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv23.l.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv23.m.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv23.m.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv23.h.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.howalk.cv23.h.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv0.l.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv0.l.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv0.m.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv0.m.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv0.h.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv0.h.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv1.l.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv1.l.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv1.m.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv1.m.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv1.h.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv1.h.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv23.l.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv23.l.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv23.m.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv23.m.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv23.h.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrwalk.cv23.h.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv0.l.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv0.l.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv0.m.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv0.m.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv0.h.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv0.h.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv1.l.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv1.l.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv1.m.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv1.m.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv1.h.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv1.h.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv23.l.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv23.l.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv23.m.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv23.m.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv23.h.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hswalk.cv23.h.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv0.l.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv0.l.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv0.m.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv0.m.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv0.h.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv0.h.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv1.l.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv1.l.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv1.m.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv1.m.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv1.h.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv1.h.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv23.l.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv23.l.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv23.m.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv23.m.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv23.h.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwwalk.cv23.h.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv0.l.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv0.l.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv0.m.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv0.m.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv0.h.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv0.h.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv1.l.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv1.l.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv1.m.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv1.m.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv1.h.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv1.h.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv23.l.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv23.l.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv23.m.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv23.m.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv23.h.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwwalk.cv23.h.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv0.l.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv0.l.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv0.m.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv0.m.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv0.h.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv0.h.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv1.l.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv1.l.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv1.m.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv1.m.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv1.h.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv1.h.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv23.l.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv23.l.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv23.m.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv23.m.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv23.h.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwwalk.cv23.h.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_sch.omx","mf.schwalk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv0.l.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv0.l.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv0.m.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv0.m.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv0.h.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv0.h.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv1.l.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv1.l.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv1.m.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv1.m.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv1.h.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv1.h.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv23.l.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv23.l.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv23.m.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv23.m.op")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv23.h.pk")
build_walk_trips = build_walk_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcwalk.cv23.h.op")

build_bike_trips = read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv0.l.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv0.m.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv0.m.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv0.h.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv0.h.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv1.l.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv1.l.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv1.m.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv1.m.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv1.h.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv1.h.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv23.l.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv23.l.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv23.m.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv23.m.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv23.h.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_ho.omx","mf.hobike.cv23.h.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv0.l.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv0.l.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv0.m.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv0.m.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv0.h.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv0.h.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv1.l.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv1.l.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv1.m.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv1.m.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv1.h.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv1.h.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv23.l.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv23.l.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv23.m.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv23.m.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv23.h.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hr.omx","mf.hrbike.cv23.h.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv0.l.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv0.l.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv0.m.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv0.m.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv0.h.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv0.h.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv1.l.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv1.l.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv1.m.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv1.m.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv1.h.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv1.h.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv23.l.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv23.l.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv23.m.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv23.m.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv23.h.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hs.omx","mf.hsbike.cv23.h.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv0.l.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv0.l.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv0.m.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv0.m.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv0.h.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv0.h.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv1.l.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv1.l.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv1.m.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv1.m.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv1.h.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv1.h.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv23.l.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv23.l.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv23.m.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv23.m.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv23.h.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hw.omx","mf.hwbike.cv23.h.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv0.l.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv0.l.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv0.m.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv0.m.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv0.h.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv0.h.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv1.l.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv1.l.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv1.m.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv1.m.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv1.h.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv1.h.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv23.l.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv23.l.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv23.m.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv23.m.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv23.h.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhw.omx","mf.nhwbike.cv23.h.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv0.l.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv0.l.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv0.m.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv0.m.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv0.h.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv0.h.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv1.l.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv1.l.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv1.m.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv1.m.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv1.h.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv1.h.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv23.l.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv23.l.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv23.m.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv23.m.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv23.h.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_nhnw.omx","mf.nhnwbike.cv23.h.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_sch.omx","mf.schbike")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv0.l.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv0.l.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv0.m.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv0.m.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv0.h.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv0.h.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv1.l.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv1.l.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv1.m.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv1.m.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv1.h.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv1.h.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv23.l.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv23.l.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv23.m.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv23.m.op")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv23.h.pk")
build_bike_trips = build_bike_trips + read_omx("mce_input_mode_choice_pa_hc.omx","mf.hcbike.cv23.h.op")

#calculate average walk and bike time
print("calculate average walk and bike time")
base_walk_time = base_wdist * (60 / WALK_SPEED)
build_walk_time = build_wdist * (60 / WALK_SPEED)
base_bike_time = base_tdist * (60 / BIKE_SPEED)
build_bike_time = build_tdist * (60 / BIKE_SPEED)

#loop by coc
dalys = list()
for(coc in colnames(cocs)) {
  if(coc=="ID") { next } # skip
  if(is.factor(cocs[,coc])) { next } # skip

  #assume coc shares for trips by production zone
  print("assume coc shares for trips by production zone")
  coc_shares = cocs[,coc]
  coc_persons = coc_shares * rowSums(cvals) * AVG_HH_SIZE

  #amount of time walking by coc
  print("amount of time walking by coc")
  coc_shares = matrix(coc_shares, length(coc_shares), length(coc_shares))
  base_amount_of_time_walking = base_walk_trips * base_walk_time * coc_shares
  build_amount_of_time_walking = build_walk_trips * build_walk_time * coc_shares
  base_amount_of_time_biking = base_bike_trips * base_bike_time * coc_shares
  build_amount_of_time_biking = build_bike_trips * build_bike_time * coc_shares
  
  base_avg_walk_time = sum(base_amount_of_time_walking) / sum(coc_persons)
  build_avg_walk_time = sum(build_amount_of_time_walking) / sum(coc_persons)
  base_avg_bike_time = sum(base_amount_of_time_biking) / sum(coc_persons)
  build_avg_bike_time = sum(build_amount_of_time_biking) / sum(coc_persons)
  
  #create active transportation time files by coc
  print("create active transportation time files by coc")
  setwd(init_dir)
  ageClasses = paste0("ageClass", 1:8)
  sex = c("M","F")
  mode = c("walk","cycle")
  activeTransportTime = expand.grid(ageClasses,sex,mode,0)
  colnames(activeTransportTime) = c("ageClass","sex","mode","value")
  
  activeTransportTime$value = base_avg_walk_time
  activeTransportTime$value[activeTransportTime$mode=="cycle"] = base_avg_bike_time
  atFile_base = paste0(projectDirectory_run,  "/", coc, "_activeTransportTime.csv") #mean walk and cycle times
  write.csv(activeTransportTime, atFile_base, row.names=F)
  
  activeTransportTime$value = build_avg_walk_time
  activeTransportTime$value[activeTransportTime$mode=="cycle"] = build_avg_bike_time
  atFile_build = paste0(projectDirectory_run,  "/", coc, "_activeTransportTime_scenario.csv")
  write.csv(activeTransportTime, atFile_build, row.names=F)
  
  #run ithim by coc
  print("run ithim by coc")
  ITHIM.baseline = createITHIM(atFile_base, paste0(projectDirectory_run,  "/", GBDFileForITHIM), paste0(projectDirectory_run,  "/", PopulationFileForITHIM))
  ITHIM.scenario = createITHIM(atFile_build, paste0(projectDirectory_run,  "/", GBDFileForITHIM), paste0(projectDirectory_run,  "/", PopulationFileForITHIM))
  dalys_coc = deltaBurden(ITHIM.baseline, ITHIM.scenario, dis = "all", bur = "daly")
  dalys = c(dalys, list(c(coc, dalys_coc)))
  print(paste0(coc, " dalys: ", dalys_coc))
}

#write output file
print("write output file")
dalys = data.frame(t(data.frame(dalys)))
colnames(dalys) = c("coc","dalys")
dalys = data.frame(coc=as.character(dalys$coc), dalys=as.double(as.character(dalys$dalys)))
dalys["dollars"] = dalys["dalys"] * DOLLARS_PER_DALY
dalys_file = paste0(projectDirectory_run,  "/dalys_cocs.csv")
write.csv(dalys, dalys_file, row.names=F)
